// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: com/google/transit/realtime/gtfs-realtime-MTARR.proto

package mtarr

import (
	gtfs "github.com/MobilityData/gtfs-realtime-bindings/golang/gtfs"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Whether the carriage has toilet facilities onboard.
type MtaRailroadCarriageDetails_QuietCarriage int32

const (
	// It is unknown if the carriage is designated as a quiet carriage.
	//
	//	This is the default case.
	MtaRailroadCarriageDetails_UNKNOWN_QUIET_CARRIAGE MtaRailroadCarriageDetails_QuietCarriage = 0
	// The carriage is designated a quiet carriage.
	MtaRailroadCarriageDetails_QUIET_CARRIAGE MtaRailroadCarriageDetails_QuietCarriage = 1
	// The carriage is not designated as a quiet carriage.
	MtaRailroadCarriageDetails_NOT_QUIET_CARRIAGE MtaRailroadCarriageDetails_QuietCarriage = 2
)

// Enum value maps for MtaRailroadCarriageDetails_QuietCarriage.
var (
	MtaRailroadCarriageDetails_QuietCarriage_name = map[int32]string{
		0: "UNKNOWN_QUIET_CARRIAGE",
		1: "QUIET_CARRIAGE",
		2: "NOT_QUIET_CARRIAGE",
	}
	MtaRailroadCarriageDetails_QuietCarriage_value = map[string]int32{
		"UNKNOWN_QUIET_CARRIAGE": 0,
		"QUIET_CARRIAGE":         1,
		"NOT_QUIET_CARRIAGE":     2,
	}
)

func (x MtaRailroadCarriageDetails_QuietCarriage) Enum() *MtaRailroadCarriageDetails_QuietCarriage {
	p := new(MtaRailroadCarriageDetails_QuietCarriage)
	*p = x
	return p
}

func (x MtaRailroadCarriageDetails_QuietCarriage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MtaRailroadCarriageDetails_QuietCarriage) Descriptor() protoreflect.EnumDescriptor {
	return file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_enumTypes[0].Descriptor()
}

func (MtaRailroadCarriageDetails_QuietCarriage) Type() protoreflect.EnumType {
	return &file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_enumTypes[0]
}

func (x MtaRailroadCarriageDetails_QuietCarriage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *MtaRailroadCarriageDetails_QuietCarriage) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = MtaRailroadCarriageDetails_QuietCarriage(num)
	return nil
}

// Deprecated: Use MtaRailroadCarriageDetails_QuietCarriage.Descriptor instead.
func (MtaRailroadCarriageDetails_QuietCarriage) EnumDescriptor() ([]byte, []int) {
	return file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_rawDescGZIP(), []int{1, 0}
}

// Whether the carriage has toilet facilities onboard.
type MtaRailroadCarriageDetails_ToiletFacilities int32

const (
	// It is unknown if the carriage has toilet facilities. This is the
	// default case.
	MtaRailroadCarriageDetails_UNKNOWN_TOILET_FACILITIES MtaRailroadCarriageDetails_ToiletFacilities = 0
	// The carriage has toilet facilities onboard.
	MtaRailroadCarriageDetails_TOILET_ONBOARD MtaRailroadCarriageDetails_ToiletFacilities = 1
	// The carriage does not have toilet facilities onboard.
	MtaRailroadCarriageDetails_NO_TOILET_ONBOARD MtaRailroadCarriageDetails_ToiletFacilities = 2
)

// Enum value maps for MtaRailroadCarriageDetails_ToiletFacilities.
var (
	MtaRailroadCarriageDetails_ToiletFacilities_name = map[int32]string{
		0: "UNKNOWN_TOILET_FACILITIES",
		1: "TOILET_ONBOARD",
		2: "NO_TOILET_ONBOARD",
	}
	MtaRailroadCarriageDetails_ToiletFacilities_value = map[string]int32{
		"UNKNOWN_TOILET_FACILITIES": 0,
		"TOILET_ONBOARD":            1,
		"NO_TOILET_ONBOARD":         2,
	}
)

func (x MtaRailroadCarriageDetails_ToiletFacilities) Enum() *MtaRailroadCarriageDetails_ToiletFacilities {
	p := new(MtaRailroadCarriageDetails_ToiletFacilities)
	*p = x
	return p
}

func (x MtaRailroadCarriageDetails_ToiletFacilities) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MtaRailroadCarriageDetails_ToiletFacilities) Descriptor() protoreflect.EnumDescriptor {
	return file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_enumTypes[1].Descriptor()
}

func (MtaRailroadCarriageDetails_ToiletFacilities) Type() protoreflect.EnumType {
	return &file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_enumTypes[1]
}

func (x MtaRailroadCarriageDetails_ToiletFacilities) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *MtaRailroadCarriageDetails_ToiletFacilities) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = MtaRailroadCarriageDetails_ToiletFacilities(num)
	return nil
}

// Deprecated: Use MtaRailroadCarriageDetails_ToiletFacilities.Descriptor instead.
func (MtaRailroadCarriageDetails_ToiletFacilities) EnumDescriptor() ([]byte, []int) {
	return file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_rawDescGZIP(), []int{1, 1}
}

type MtaRailroadStopTimeUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Track         *string                `protobuf:"bytes,1,opt,name=track" json:"track,omitempty"`
	TrainStatus   *string                `protobuf:"bytes,2,opt,name=trainStatus" json:"trainStatus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MtaRailroadStopTimeUpdate) Reset() {
	*x = MtaRailroadStopTimeUpdate{}
	mi := &file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MtaRailroadStopTimeUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MtaRailroadStopTimeUpdate) ProtoMessage() {}

func (x *MtaRailroadStopTimeUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MtaRailroadStopTimeUpdate.ProtoReflect.Descriptor instead.
func (*MtaRailroadStopTimeUpdate) Descriptor() ([]byte, []int) {
	return file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_rawDescGZIP(), []int{0}
}

func (x *MtaRailroadStopTimeUpdate) GetTrack() string {
	if x != nil && x.Track != nil {
		return *x.Track
	}
	return ""
}

func (x *MtaRailroadStopTimeUpdate) GetTrainStatus() string {
	if x != nil && x.TrainStatus != nil {
		return *x.TrainStatus
	}
	return ""
}

type MtaRailroadCarriageDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Indicates the number of bikes permitted per carriage.
	// 0=bikes prohibited, -1=No limit.
	BicyclesAllowed *int32 `protobuf:"varint,1,opt,name=bicycles_allowed,json=bicyclesAllowed,def=0" json:"bicycles_allowed,omitempty"`
	// A description of the carriage type/model.
	CarriageClass    *string                                      `protobuf:"bytes,2,opt,name=carriage_class,json=carriageClass" json:"carriage_class,omitempty"`
	QuietCarriage    *MtaRailroadCarriageDetails_QuietCarriage    `protobuf:"varint,3,opt,name=quiet_carriage,json=quietCarriage,enum=transit_realtime.MtaRailroadCarriageDetails_QuietCarriage,def=0" json:"quiet_carriage,omitempty"`
	ToiletFacilities *MtaRailroadCarriageDetails_ToiletFacilities `protobuf:"varint,4,opt,name=toilet_facilities,json=toiletFacilities,enum=transit_realtime.MtaRailroadCarriageDetails_ToiletFacilities,def=0" json:"toilet_facilities,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

// Default values for MtaRailroadCarriageDetails fields.
const (
	Default_MtaRailroadCarriageDetails_BicyclesAllowed  = int32(0)
	Default_MtaRailroadCarriageDetails_QuietCarriage    = MtaRailroadCarriageDetails_UNKNOWN_QUIET_CARRIAGE
	Default_MtaRailroadCarriageDetails_ToiletFacilities = MtaRailroadCarriageDetails_UNKNOWN_TOILET_FACILITIES
)

func (x *MtaRailroadCarriageDetails) Reset() {
	*x = MtaRailroadCarriageDetails{}
	mi := &file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MtaRailroadCarriageDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MtaRailroadCarriageDetails) ProtoMessage() {}

func (x *MtaRailroadCarriageDetails) ProtoReflect() protoreflect.Message {
	mi := &file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MtaRailroadCarriageDetails.ProtoReflect.Descriptor instead.
func (*MtaRailroadCarriageDetails) Descriptor() ([]byte, []int) {
	return file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_rawDescGZIP(), []int{1}
}

func (x *MtaRailroadCarriageDetails) GetBicyclesAllowed() int32 {
	if x != nil && x.BicyclesAllowed != nil {
		return *x.BicyclesAllowed
	}
	return Default_MtaRailroadCarriageDetails_BicyclesAllowed
}

func (x *MtaRailroadCarriageDetails) GetCarriageClass() string {
	if x != nil && x.CarriageClass != nil {
		return *x.CarriageClass
	}
	return ""
}

func (x *MtaRailroadCarriageDetails) GetQuietCarriage() MtaRailroadCarriageDetails_QuietCarriage {
	if x != nil && x.QuietCarriage != nil {
		return *x.QuietCarriage
	}
	return Default_MtaRailroadCarriageDetails_QuietCarriage
}

func (x *MtaRailroadCarriageDetails) GetToiletFacilities() MtaRailroadCarriageDetails_ToiletFacilities {
	if x != nil && x.ToiletFacilities != nil {
		return *x.ToiletFacilities
	}
	return Default_MtaRailroadCarriageDetails_ToiletFacilities
}

var file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*gtfs.TripUpdate_StopTimeUpdate)(nil),
		ExtensionType: (*MtaRailroadStopTimeUpdate)(nil),
		Field:         1005,
		Name:          "transit_realtime.mta_railroad_stop_time_update",
		Tag:           "bytes,1005,opt,name=mta_railroad_stop_time_update",
		Filename:      "com/google/transit/realtime/gtfs-realtime-MTARR.proto",
	},
	{
		ExtendedType:  (*gtfs.VehiclePosition_CarriageDetails)(nil),
		ExtensionType: (*MtaRailroadCarriageDetails)(nil),
		Field:         1005,
		Name:          "transit_realtime.mta_railroad_carriage_details",
		Tag:           "bytes,1005,opt,name=mta_railroad_carriage_details",
		Filename:      "com/google/transit/realtime/gtfs-realtime-MTARR.proto",
	},
}

// Extension fields to gtfs.TripUpdate_StopTimeUpdate.
var (
	// optional transit_realtime.MtaRailroadStopTimeUpdate mta_railroad_stop_time_update = 1005;
	E_MtaRailroadStopTimeUpdate = &file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_extTypes[0]
)

// Extension fields to gtfs.VehiclePosition_CarriageDetails.
var (
	// optional transit_realtime.MtaRailroadCarriageDetails mta_railroad_carriage_details = 1005;
	E_MtaRailroadCarriageDetails = &file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_extTypes[1]
)

var File_com_google_transit_realtime_gtfs_realtime_MTARR_proto protoreflect.FileDescriptor

const file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_rawDesc = "" +
	"\n" +
	"5com/google/transit/realtime/gtfs-realtime-MTARR.proto\x12\x10transit_realtime\x1a/com/google/transit/realtime/gtfs-realtime.proto\"S\n" +
	"\x19MtaRailroadStopTimeUpdate\x12\x14\n" +
	"\x05track\x18\x01 \x01(\tR\x05track\x12 \n" +
	"\vtrainStatus\x18\x02 \x01(\tR\vtrainStatus\"\xab\x04\n" +
	"\x1aMtaRailroadCarriageDetails\x12,\n" +
	"\x10bicycles_allowed\x18\x01 \x01(\x05:\x010R\x0fbicyclesAllowed\x12%\n" +
	"\x0ecarriage_class\x18\x02 \x01(\tR\rcarriageClass\x12y\n" +
	"\x0equiet_carriage\x18\x03 \x01(\x0e2:.transit_realtime.MtaRailroadCarriageDetails.QuietCarriage:\x16UNKNOWN_QUIET_CARRIAGER\rquietCarriage\x12\x85\x01\n" +
	"\x11toilet_facilities\x18\x04 \x01(\x0e2=.transit_realtime.MtaRailroadCarriageDetails.ToiletFacilities:\x19UNKNOWN_TOILET_FACILITIESR\x10toiletFacilities\"W\n" +
	"\rQuietCarriage\x12\x1a\n" +
	"\x16UNKNOWN_QUIET_CARRIAGE\x10\x00\x12\x12\n" +
	"\x0eQUIET_CARRIAGE\x10\x01\x12\x16\n" +
	"\x12NOT_QUIET_CARRIAGE\x10\x02\"\\\n" +
	"\x10ToiletFacilities\x12\x1d\n" +
	"\x19UNKNOWN_TOILET_FACILITIES\x10\x00\x12\x12\n" +
	"\x0eTOILET_ONBOARD\x10\x01\x12\x15\n" +
	"\x11NO_TOILET_ONBOARD\x10\x02:\x9b\x01\n" +
	"\x1dmta_railroad_stop_time_update\x12+.transit_realtime.TripUpdate.StopTimeUpdate\x18\xed\a \x01(\v2+.transit_realtime.MtaRailroadStopTimeUpdateR\x19mtaRailroadStopTimeUpdate:\xa3\x01\n" +
	"\x1dmta_railroad_carriage_details\x121.transit_realtime.VehiclePosition.CarriageDetails\x18\xed\a \x01(\v2,.transit_realtime.MtaRailroadCarriageDetailsR\x1amtaRailroadCarriageDetailsB\x1d\n" +
	"\x1bcom.google.transit.realtime"

var (
	file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_rawDescOnce sync.Once
	file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_rawDescData []byte
)

func file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_rawDescGZIP() []byte {
	file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_rawDescOnce.Do(func() {
		file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_rawDesc), len(file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_rawDesc)))
	})
	return file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_rawDescData
}

var file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_goTypes = []any{
	(MtaRailroadCarriageDetails_QuietCarriage)(0),    // 0: transit_realtime.MtaRailroadCarriageDetails.QuietCarriage
	(MtaRailroadCarriageDetails_ToiletFacilities)(0), // 1: transit_realtime.MtaRailroadCarriageDetails.ToiletFacilities
	(*MtaRailroadStopTimeUpdate)(nil),                // 2: transit_realtime.MtaRailroadStopTimeUpdate
	(*MtaRailroadCarriageDetails)(nil),               // 3: transit_realtime.MtaRailroadCarriageDetails
	(*gtfs.TripUpdate_StopTimeUpdate)(nil),           // 4: transit_realtime.TripUpdate.StopTimeUpdate
	(*gtfs.VehiclePosition_CarriageDetails)(nil),     // 5: transit_realtime.VehiclePosition.CarriageDetails
}
var file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_depIdxs = []int32{
	0, // 0: transit_realtime.MtaRailroadCarriageDetails.quiet_carriage:type_name -> transit_realtime.MtaRailroadCarriageDetails.QuietCarriage
	1, // 1: transit_realtime.MtaRailroadCarriageDetails.toilet_facilities:type_name -> transit_realtime.MtaRailroadCarriageDetails.ToiletFacilities
	4, // 2: transit_realtime.mta_railroad_stop_time_update:extendee -> transit_realtime.TripUpdate.StopTimeUpdate
	5, // 3: transit_realtime.mta_railroad_carriage_details:extendee -> transit_realtime.VehiclePosition.CarriageDetails
	2, // 4: transit_realtime.mta_railroad_stop_time_update:type_name -> transit_realtime.MtaRailroadStopTimeUpdate
	3, // 5: transit_realtime.mta_railroad_carriage_details:type_name -> transit_realtime.MtaRailroadCarriageDetails
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	4, // [4:6] is the sub-list for extension type_name
	2, // [2:4] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_init() }
func file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_init() {
	if File_com_google_transit_realtime_gtfs_realtime_MTARR_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_rawDesc), len(file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_goTypes,
		DependencyIndexes: file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_depIdxs,
		EnumInfos:         file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_enumTypes,
		MessageInfos:      file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_msgTypes,
		ExtensionInfos:    file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_extTypes,
	}.Build()
	File_com_google_transit_realtime_gtfs_realtime_MTARR_proto = out.File
	file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_goTypes = nil
	file_com_google_transit_realtime_gtfs_realtime_MTARR_proto_depIdxs = nil
}
